name: ci prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-19.04
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2