name: ci prettier

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, prettier
        run: |
          yarn install
          yarn prettier --write src/*
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: 'prettier: Apply Prettier Change'
